import assert from "node:assert/strict"
import test from "node:test"
import { readFile } from "node:fs/promises"
import { buildScheduleDocumentModel, createSchedulePdfRenderer } from "../domain/schedule-pdf/index.ts"
import { migrateData } from "../lib/storage.ts"
import { EMPTY_APP_DATA, MODULE_PRESET_SEEDS } from "../lib/types.ts"

test("presets mañana tarde noche son semillas de un módulo", () => { assert.deepEqual(Object.values(MODULE_PRESET_SEEDS).map((seed) => [seed.start, seed.end]), [["07:30", "08:15"], ["13:30", "14:15"], ["18:30", "19:15"]]) })
test("legacy Mon-Fri migra y enableSaturday conserva sábado", () => { const weekdays = migrateData({ ...EMPTY_APP_DATA, version: 5 } as never); assert.deepEqual(weekdays.settings.visibleScheduleDays, ["lunes", "martes", "miercoles", "jueves", "viernes"]); const saturday = migrateData({ ...EMPTY_APP_DATA, version: 5, settings: { ...EMPTY_APP_DATA.settings, enableSaturday: true, visibleScheduleDays: undefined } } as never); assert.ok(saturday.settings.visibleScheduleDays.includes("sabado")) })
test("PDF real 8 módulos y lunes-jueves queda en una página y omite viernes", async () => { const modules = Array.from({ length: 8 }, (_, index) => ({ id: `m${index}`, label: `Módulo ${index + 1}`, start: `${String(8 + index).padStart(2, "0")}:00`, end: `${String(8 + index).padStart(2, "0")}:45` })); const days = ["lunes", "martes", "miercoles", "jueves"] as const; const model = buildScheduleDocumentModel({ profile: { displayName: "Estudiante" }, semester: { id: "s", name: "2026" }, subjects: [{ id: "x", name: "Sistemas electroneumáticos industriales con nombre largo", color: "#334455" }], modules, schedule: modules.map((module, index) => ({ subjectId: "x", day: days[index % 4], moduleIds: [module.id] })), visibleDays: [...days], generatedAt: new Date("2026-08-12T00:00:00Z") }); assert.equal(model.entries.length, 8); const pdf = await createSchedulePdfRenderer().render(model); const source = Buffer.from(pdf.bytes).toString("latin1"); assert.equal((source.match(/\/Type \/Page\b/g) ?? []).length, 1); assert.doesNotMatch(source, /Viernes/); assert.match(source, /Horarily/) })
test("Orbit se resuelve como componente y no se concatena como prefijo", async () => { const notebook = await readFile("components/notebook/notebook-view.tsx", "utf8"); assert.match(notebook, /getLucideIcon\(subject\.icon\)/); assert.doesNotMatch(notebook, /subject\.icon\s*\?\?/) })
test("editores de módulos conservan draft hasta Guardar", async () => { const settings = await readFile("components/time-modules-editor.tsx", "utf8"); const schedule = await readFile("components/schedule-grid.tsx", "utf8"); assert.match(settings, /useState\(module\)/); assert.match(settings, /onSave\(draft\)/); assert.match(schedule, /setEditingModule\(\{ \.\.\.mod \}\)/); assert.match(schedule, /Cancelar/); assert.match(schedule, /editingModule\.start >= editingModule\.end/) })
