"use client"
import { useEffect, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"

type Stroke = { color: string; width: number; points: { x: number; y: number }[] }
export function DrawingCanvas({ open, onOpenChange, onInsert }: { open: boolean; onOpenChange: (open: boolean) => void; onInsert: (blob: Blob) => void }) {
  const canvas = useRef<HTMLCanvasElement>(null); const [strokes, setStrokes] = useState<Stroke[]>([]); const [redo, setRedo] = useState<Stroke[]>([]); const [width, setWidth] = useState(3); const [eraser, setEraser] = useState(false); const active = useRef<Stroke | null>(null)
  const draw = () => { const node = canvas.current; if (!node) return; const context = node.getContext("2d"); if (!context) return; context.clearRect(0, 0, node.width, node.height); context.fillStyle = "white"; context.fillRect(0, 0, node.width, node.height); for (const stroke of strokes) { context.strokeStyle = stroke.color; context.lineWidth = stroke.width; context.lineCap = "round"; context.beginPath(); stroke.points.forEach((point, index) => index ? context.lineTo(point.x, point.y) : context.moveTo(point.x, point.y)); context.stroke() } }
  useEffect(draw, [strokes])
  const point = (event: React.PointerEvent) => { const rect = canvas.current!.getBoundingClientRect(); return { x: (event.clientX - rect.left) * canvas.current!.width / rect.width, y: (event.clientY - rect.top) * canvas.current!.height / rect.height } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Dibujar</DialogTitle><DialogDescription>Compatible con mouse, dedo y lápiz táctil.</DialogDescription></DialogHeader><div className="flex flex-wrap gap-2"><Button variant={!eraser ? "default" : "outline"} onClick={() => setEraser(false)}>Lápiz</Button><Button variant={eraser ? "default" : "outline"} onClick={() => setEraser(true)}>Borrador</Button><label className="flex items-center gap-2 text-sm">Grosor <input type="range" min="1" max="18" value={width} onChange={(e) => setWidth(Number(e.target.value))} /></label><Button variant="outline" disabled={!strokes.length} onClick={() => { setRedo([strokes.at(-1)!, ...redo]); setStrokes(strokes.slice(0, -1)) }}>Deshacer</Button><Button variant="outline" disabled={!redo.length} onClick={() => { setStrokes([...strokes, redo[0]]); setRedo(redo.slice(1)) }}>Rehacer</Button><Button variant="destructive" onClick={() => { setStrokes([]); setRedo([]) }}>Limpiar</Button></div><canvas ref={canvas} width={1000} height={560} aria-label="Lienzo para dibujo o escritura manual" className="w-full touch-none rounded-lg border bg-white" onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); active.current = { color: eraser ? "#ffffff" : "#111827", width: eraser ? width * 3 : width, points: [point(event)] }; setRedo([]) }} onPointerMove={(event) => { if (!active.current) return; active.current.points.push(point(event)); setStrokes([...strokes, { ...active.current }]) }} onPointerUp={() => { active.current = null }} /><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={!strokes.length} onClick={() => canvas.current?.toBlob((blob) => { if (blob) onInsert(blob) }, "image/png")}>Insertar dibujo</Button></DialogFooter></DialogContent></Dialog>
}
