"use client"
import { useEffect, useRef, useState } from "react"
import { Button } from "@/components/ui/button"

type Stroke = { color: string; width: number; points: { x: number; y: number }[] }
export function DrawingCanvas({ open, onOpenChange, onInsert }: { open: boolean; onOpenChange: (open: boolean) => void; onInsert: (blob: Blob) => Promise<unknown> | unknown }) {
  const canvas = useRef<HTMLCanvasElement>(null); const [strokes, setStrokes] = useState<Stroke[]>([]); const [redo, setRedo] = useState<Stroke[]>([]); const [width, setWidth] = useState(3); const [eraser, setEraser] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const active = useRef<Stroke | null>(null)
  const draw = () => { const node = canvas.current; if (!node) return; const context = node.getContext("2d"); if (!context) return; context.clearRect(0, 0, node.width, node.height); context.fillStyle = "white"; context.fillRect(0, 0, node.width, node.height); for (const stroke of strokes) { context.strokeStyle = stroke.color; context.lineWidth = stroke.width; context.lineCap = "round"; context.beginPath(); stroke.points.forEach((point, index) => index ? context.lineTo(point.x, point.y) : context.moveTo(point.x, point.y)); context.stroke() } }
  useEffect(draw, [strokes])
  const point = (event: React.PointerEvent) => { const rect = canvas.current!.getBoundingClientRect(); return { x: (event.clientX - rect.left) * canvas.current!.width / rect.width, y: (event.clientY - rect.top) * canvas.current!.height / rect.height } }
  if (!open) return null
  const finish = () => canvas.current?.toBlob((blob) => { if (!blob) return; setSaving(true); setError(""); void Promise.resolve(onInsert(blob)).catch((reason) => setError(reason instanceof Error ? reason.message : "No se pudo insertar el dibujo.")).finally(() => setSaving(false)) }, "image/png")
  return <section className="space-y-3 rounded-xl border bg-muted/20 p-3" aria-label="Dibujo inline"><div><h3 className="font-medium">Dibujar dentro del apunte</h3><p className="text-sm text-muted-foreground">Compatible con mouse, dedo y lápiz táctil.</p></div><div className="flex flex-wrap gap-2"><Button variant={!eraser ? "default" : "outline"} onClick={() => setEraser(false)}>Lápiz</Button><Button variant={eraser ? "default" : "outline"} onClick={() => setEraser(true)}>Borrador</Button><label className="flex items-center gap-2 text-sm">Grosor <input type="range" min="1" max="18" value={width} onChange={(e) => setWidth(Number(e.target.value))} /></label><Button variant="outline" disabled={!strokes.length} onClick={() => { setRedo([strokes.at(-1)!, ...redo]); setStrokes(strokes.slice(0, -1)) }}>Deshacer</Button><Button variant="outline" disabled={!redo.length} onClick={() => { setStrokes([...strokes, redo[0]]); setRedo(redo.slice(1)) }}>Rehacer</Button><Button variant="destructive" onClick={() => { setStrokes([]); setRedo([]) }}>Limpiar</Button></div><canvas ref={canvas} width={1000} height={560} aria-label="Lienzo para dibujo o escritura manual" className="w-full touch-none rounded-lg border bg-white" onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); active.current = { color: eraser ? "#ffffff" : "#111827", width: eraser ? width * 3 : width, points: [point(event)] }; setRedo([]) }} onPointerMove={(event) => { if (!active.current) return; active.current.points.push(point(event)); setStrokes([...strokes, { ...active.current }]) }} onPointerUp={() => { active.current = null }} /><div className="flex justify-end gap-2"><Button variant="outline" disabled={saving} onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={!strokes.length || saving} onClick={finish}>{saving ? "Guardando dibujo…" : "Listo"}</Button></div>{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}</section>
}
