"use client"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { buildAcademicAgenda } from "@/domain/academic-agenda"
import type { ScheduleStore } from "@/hooks/use-schedule-store"
export function AcademicAgendaPanel({ store, onNavigate }: { store: ScheduleStore; onNavigate: (tab: string) => void }) {
  const data = store.data
  const agenda = buildAcademicAgenda({ now: new Date(), semesterId: data.activeSemesterId ?? "", timezone: data.profile.timezone, subjects: data.subjects.map((subject) => ({ id: subject.id, name: subject.name })), assessments: data.grades.map((grade) => ({ ...grade, groupId: grade.groupId ?? "", weightWithinGroup: grade.weightWithinGroup ?? grade.weight, scheduledDate: grade.date, status: grade.status ?? (grade.score === null ? "planned" : "graded") })), classes: data.blocks.map((block) => ({ id: block.id, semesterId: block.semesterId, subjectId: block.subjectId, day: block.day, start: data.modules.find((module) => module.id === block.moduleIds[0])?.start ?? "08:00", end: data.modules.find((module) => module.id === block.moduleIds.at(-1))?.end ?? "08:45", title: data.subjects.find((subject) => subject.id === block.subjectId)?.name })), studyBlocks: data.studyBlocks.map((block) => ({ ...block })), reminders: data.reminders })
  return <Card><CardHeader><CardTitle>Agenda académica</CardTitle><CardDescription>Evaluaciones, recordatorios, estudio, clases y vencidas sin nota.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Button size="sm" variant="outline">7 días</Button><Button size="sm" variant="outline">30 días</Button><Button size="sm" variant="outline">Por asignatura</Button></div>{agenda.next30Days.slice(0, 8).map((item) => <div key={`${item.kind}-${item.id}`} className="flex items-center justify-between rounded-md border p-2 text-sm"><span>{item.title} · {item.kind}</span><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => onNavigate("notas")}>Abrir evaluación</Button><Button size="sm" variant="ghost" onClick={() => onNavigate("estudio")}>Crear estudio</Button><Button size="sm" variant="ghost" onClick={() => onNavigate("recordatorios")}>Crear recordatorio</Button><Button size="sm" variant="ghost" onClick={() => onNavigate("materias")}>Ir a asignatura</Button></div></div>)}{agenda.next30Days.length === 0 && <p className="text-sm text-muted-foreground">No hay eventos próximos.</p>}</CardContent></Card>
}
